<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>움직이는 지도로 표현하기</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>





<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h1>움직이는 지도로 표현하기</h1>

<p>Dr.Kevin
8/1/2018</p>

<p><a href="https://mrkevinna.github.io/R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-2/">지난 포스팅</a>에서 행정경계구역 데이터를 전처리하고 단계구분도를 그려보았습니다. 이번에는 움직이는 지도로 표현하는 방법을 알아보겠습니다. <strong>leaflet</strong> 패키지를 이용하면 가능합니다.</p>

<p>이번 포스팅에서도 행정경계구역 데이터 전처리를 해야 하는데, 지난 포스팅에서 다룬 것과 다른 내용입니다. 우리나라 정부 기관은 국제 표준(?)인 <strong>WGS84</strong> 좌표계 대신 <strong>GRS80</strong> 좌표계로 된 데이터를 공공데이터로 제공하고 있습니다. 따라서 지난 포스팅에서 소개해드린 단계구분도는 별 상관 없이 그릴 수 있지만 실제 지도 위에 시각화하는 것은 좌표계를 바꿔주기 전에는 불가능합니다.</p>

<p>그러므로 GRS80 위경도 좌표를 WGS84 위경도 좌표로 바꿔주는 작업을 먼저 해야 합니다. 그리고 나서 데이터의 행 수가 매우 많으므로 이를 축소해주어야 하는데 지난 포스팅에서 사용한 방법을 쓰면 <code>leaflet()</code> 함수가 제대로 작동하지 않습니다. 따라서 지난 포스팅에서 언급했던 두 번째 방법을 이용하여 shp 파일을 크게 줄이는 방법을 소개해드리겠습니다.</p>

<pre><code class="r"># 필요 패키지를 불러옵니다. 
library(ggplot2)
library(rgdal)
library(sp)
</code></pre>

<pre><code class="r"># 단계구분도를 그릴 때 사용할 시/군/구 행정경계구역 데이터를 불러옵니다.
sigg &lt;- 
  readOGR(
    dsn = &#39;bnd_sigungu_00_2016&#39;,
    layer = &#39;bnd_sigungu_00_2016&#39;,
    encoding = &#39;CP949&#39;)
</code></pre>

<p>shp 파일을 불러왔으면 WGS84 좌표계로 변환하기 전에 위경도 좌표가 어떻게 생겼는지 육안으로 먼저 확인해보겠습니다. <code>sigg</code>는 <strong>s4 객체</strong>라서 <code>@</code>를 이용하여 하위 요소를 지정할 수 있습니다. <code>sigg@polygons</code>은 250개의 지방자치단체 경계구역 데이터를 담고 있는 리스트입니다. 첫 번째 지방자치단체의 행정경계구역 데이터가 몇 건인지 확인해보겠습니다.</p>

<pre><code class="r"># 첫 번째 행정경계구역 데이터의 개수를 확인합니다. 
sigg@polygons[[1]]@Polygons[[1]]@coords %&gt;% nrow()
</code></pre>

<pre><code>## [1] 2343
</code></pre>

<p>첫 번째 요소의 경계데이터는 총 <code>2,343</code>개임을 알 수 있습니다. 그럼 처음 10행만 확인해볼까요?</p>

<pre><code class="r"># 첫 번째 행정경계구역 데이터를 확인합니다. 
sigg@polygons[[1]]@Polygons[[1]]@coords %&gt;% head(n = 10L)
</code></pre>

<pre><code>##           [,1]    [,2]
##  [1,] 953683.8 1959210
##  [2,] 953647.3 1959057
##  [3,] 953672.0 1958971
##  [4,] 953780.2 1958977
##  [5,] 953976.8 1958998
##  [6,] 953977.1 1958998
##  [7,] 953994.1 1958990
##  [8,] 954025.5 1958974
##  [9,] 954040.2 1958968
## [10,] 954074.5 1958954
</code></pre>

<p>좌표계가 10만 단위의 경도와 100만 단위의 위도로 되어 있습니다. 이제 데이터를 WGS84 좌표계로 바꿔보겠습니다. <strong>sp</strong> 패키지의 <code>spTransform()</code> 함수를 사용하고 <code>CRSobj</code> 인자에 적당한 값을 할당하면 됩니다.</p>

<pre><code class="r"># GRS80 좌표계를 WGS84 좌표계로 변환합니다.
sigg &lt;- spTransform(x = sigg, CRSobj = CRS(&#39;+proj=longlat +datum=WGS84&#39;))

# 같은 행정경계구역 데이터를 다시 확인합니다. 
sigg@polygons[[1]]@Polygons[[1]]@coords %&gt;% head(n = 10L)
</code></pre>

<pre><code>##           [,1]     [,2]
##  [1,] 126.9751 37.63118
##  [2,] 126.9747 37.62981
##  [3,] 126.9750 37.62903
##  [4,] 126.9762 37.62909
##  [5,] 126.9784 37.62929
##  [6,] 126.9784 37.62929
##  [7,] 126.9786 37.62921
##  [8,] 126.9790 37.62908
##  [9,] 126.9791 37.62902
## [10,] 126.9795 37.62889
</code></pre>

<p>결과를 출력해보니 좌표계가 바뀌어 있습니다. 우리나라 휴전선이 <strong>38선</strong>으로 불렸다는 것을 떠올린다면 서울의 위도가 38도 아래라는 것을 짐작할 수 있을 것입니다.</p>

<p>이제 <code>sigg</code> 객체를 shp 파일로 저장합니다. 이번에는 <code>writeOGR()</code> 함수를 이용하면 됩니다. <code>dsn</code> 인자에는 shp 파일을 저장할 폴더명을 지정하고 <code>layer</code> 인자에는 파일명을 할당합니다. <code>driver</code>에는 <strong>orgDrivers</strong>에 의해 반환되는 driver 이름을 문자열로 할당하라고 되어 있지만, 솔직히 잘 모르겠습니다. 그냥 온라인 상에서 확인한 것으로 지정했습니다.</p>

<pre><code class="r"># save sigg as shapefiles
writeOGR(
  obj = sigg,
  dsn = &#39;../shp/simple&#39;,
  layer = &#39;sigungu&#39;,
  driver = &#39;ESRI Shapefile&#39;)
</code></pre>

<p><code>dns</code> 폴더에 파일명이 <strong>sigungu</strong>이고 확장자가 서로 다른 4개의 파일이 저장되어 있는지 확인하시기 바랍니다. 확장자명은 <strong>bdf, prj, shp, shx</strong>입니다. 제대로 저장되었다면 이제 <a href="http://mapshaper.org/">mapShaper</a>로 이동하여 shp 파일을 축소할 시간입니다. mapShaper를 클릭하면 웹브라우저에 아래와 같은 웹페이지가 열립니다.</p>

<p><img src="https://raw.githubusercontent.com/MrKevinNa/MrKevinNa.github.io/master/images/2018-08-01-R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-3/mapShaper_1.png" alt=""></p>

<p>화면 상단 중앙에 있는 <strong>select</strong> 버튼을 클릭하면 Windows 탐색기 또는 MacOS Finder가 열립니다. 방금 저장한 <strong>sigungu.shp</strong> 파일을 선택하면 아래와 같은 화면으로 바뀝니다.</p>

<p><img src="https://raw.githubusercontent.com/MrKevinNa/MrKevinNa.github.io/master/images/2018-08-01-R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-3/mapShaper_2.png" alt=""></p>

<p>이 상태에서 그대로 <strong>import</strong> 버튼을 클릭하면 아래 그림에서와 같이 웹브라우저에 shp 파일로 그린 지도가 출력됩니다. 그리고 오른쪽 상단에 있는 <strong>Simplyfy</strong> 버튼을 클릭하면 화면 중앙에서 보이는 것처럼 팝업창이 하나 열립니다. 이 때 맨 위에 있는 <strong>Simplification menu의 prevent shape removal</strong> 항목을 선택합니다. <strong>Method는 Visvalingam / weighted area</strong>가 기본으로 선택되어 있습니다. 변경하지 말고 이 상태로 <strong>Apply</strong> 버튼을 클릭하면 됩니다.</p>

<p><img src="https://raw.githubusercontent.com/MrKevinNa/MrKevinNa.github.io/master/images/2018-08-01-R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-3/mapShaper_3.png" alt=""></p>

<p>새로 열리는 화면 상단에 있는 메뉴를 조절하여 축소할 비율을 선택하면 됩니다. 문건웅 교수님은 <strong>웹에서 클릭만으로 하는 통계분석</strong> 책에서 <code>1.0%</code>로 설정해도 충분하다고 하셨는데요. 그 가이드를 따라 <code>1.0%</code>로 설정한 후 오른쪽 상단에서 맨 끝에 있는 <strong>Export</strong> 버튼을 클릭합니다.</p>

<p><img src="https://raw.githubusercontent.com/MrKevinNa/MrKevinNa.github.io/master/images/2018-08-01-R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-3/mapShaper_4.png" alt=""></p>

<p>마지막 화면입니다. 화면 상단 중앙에 열린 팝업에서 저장할 파일의 형태를 결정합니다. <strong>shapefile</strong>로 설정하는 것이 가장 무난합니다. 이 상태에서 <strong>Export</strong> 버튼을 클릭하면 파일이 압축된 상태로 자동 다운로드 됩니다.</p>

<p><img src="https://raw.githubusercontent.com/MrKevinNa/MrKevinNa.github.io/master/images/2018-08-01-R-%EC%A7%80%EB%8F%84-%EC%8B%9C%EA%B0%81%ED%99%94-3/mapShaper_5.png" alt=""></p>

<p>압축 파일을 풀면 맨 처음 우리가 저장했던 shp 파일과 동일한 이름의 4개 파일이 저장되어 있음을 확인할 수 있습니다. 본인의 기호에 따라 그대로 쓰셔도 무방하겠지만 저는 편의상 파일명 앞에 <strong>simple_</strong>을 추가하도록 하겠습니다. 이제 저장한 파일을 불러오도록 하겠습니다.</p>

<p>여기서 한 가지 주의해야 할 점은 <code>dsn</code>에 폴더명 대신 shp 확장자를 포함하여 지정해야 한다는 것입니다. 아직은 그 이유를 파악하지 못 했습니다만, 다음에 기회가 된다면 보완하도록 하겠습니다.</p>

<pre><code class="r"># import simple shp file
spSigg &lt;- 
  readOGR(
    dsn = &#39;../shp/simple/simple_sigungu.shp&#39;, 
    layer = &#39;simple_sigungu&#39;,
    encoding = &#39;CP949&#39;)
</code></pre>

<p>우리는 shp 파일을 축소하기 전에 첫 번째 지방자치단체의 행정경계구역 데이터 수가 <code>2,343</code>개였다는 것을 알고 있습니다. 얼마나 줄었는지 한 번 확인해 보겠습니다.</p>

<pre><code class="r"># 첫 번째 행정경계구역 데이터의 개수를 확인합니다. 
spSigg@polygons[[1]]@Polygons[[1]]@coords %&gt;% nrow()
</code></pre>

<pre><code>## [1] 210
</code></pre>

<p><code>spSigg@polygons</code> 첫 번째 요소의 행 개수가 <code>210</code>으로 출력되었습니다. 거의 <code>1/20</code> 수준으로 줄었음을 알 수 있습니다. 이제 나머지 전처리 과정을 진행하도록 하겠습니다. 한 가지 확인드리고 싶은 것은, 두 번째 포스팅에서는 <code>fortify()</code> 함수를 이용하여 <code>sigg</code> 객체에서 데이터 프레임을 추출했었는데요. 이번 포스팅에서는 <code>spSigg</code> 객체 그대로 사용합니다. 대신 <code>spSigg@data</code>에 모든 정보를 집중하고 <code>leaflet()</code> 함수를 이용하여 시각화할 때 필요한 정보를 꺼내 쓰도록 하겠습니다.</p>

<p><code>spSigg@data</code>를 보니 <strong>mapShaper</strong>를 통해 데이터를 축소하니 기존 <code>sigg</code> 객체의 <code>data</code> 요소에 있던 정보들이 모두 사라지고 <code>FID</code> 하나만 남아 있습니다. 따라서 기존 <code>sigg@data</code>의 컬럼 일부를 <code>spSigg@data</code>에 <code>cbind()</code>한 다음 새로 붙인 컬럼의 이름을 편의상 <code>siggCd</code>와 <code>siggNm</code>으로 변경하겠습니다. 그리고 나서 <code>siggCd</code>의 첫 두 글자만 추출하여 <code>sidoCd</code> 컬럼을 새로 만듭니다.</p>

<pre><code class="r"># sigg@data의 모든 컬럼을 spSigg@data에 열기준으로 붙입니다. 
spSigg@data &lt;- cbind(spSigg@data, sigg@data[, 2:4])

# 새로 붙인 컬럼의 이름을 변경합니다. 
colnames(x = spSigg@data)[2:4] &lt;- c(&#39;year&#39;, &#39;siggCd&#39;, &#39;siggNm&#39;)

# siggCd에서 앞 두 글자만 추출하여 광역시도명을 붙입니다.
spSigg@data$sidoCd &lt;- str_sub(string = spSigg@data$siggCd, start = 1, end = 2)

# 처음 10행만 미리보기 합니다. 
head(x = spSigg@data, n = 10L)
</code></pre>

<pre><code>##   FID year siggCd   siggNm sidoCd
## 0   0 2016  11010   종로구     11
## 1   1 2016  11020     중구     11
## 2   2 2016  11030   용산구     11
## 3   3 2016  11040   성동구     11
## 4   4 2016  11050   광진구     11
## 5   5 2016  11060 동대문구     11
## 6   6 2016  11070   중랑구     11
## 7   7 2016  11080   성북구     11
## 8   8 2016  11090   강북구     11
## 9   9 2016  11100   도봉구     11
</code></pre>

<p>다음으로 선거 결과 데이터인 <code>result</code> 객체와 병합할 때 기준 컬럼을 만들어야 합니다. 우선 <strong>광역시도</strong> 행정경계구역 데이터를 불러온 후, <code>SIDO_CD</code>와 <code>SIDO_NM</code> 컬럼만으로 <strong>sidoGb</strong> 객체를 하나 만들고 컬럼명을 <code>sidoCd</code>와 <code>sidoNm</code>으로 변경한 다음 <code>spSigg@data</code>와 병합합니다. 그리고 나서 <code>sidoNm</code>과 <code>siggNm</code>을 붙인 <code>areaNm</code> 컬럼을 새로 만듭니다. 이 부분은 지난 포스팅에서 소개해드린 것과 동일합니다.</p>

<pre><code class="r"># 광역시도명 코드와 이름을 얻기 위해 시도 행정경계구역 데이터를 불러옵니다.
sido &lt;- 
  readOGR(
    dsn = &#39;bnd_sido_00_2016&#39;,
    layer = &#39;bnd_sido_00_2016&#39;,
    encoding = &#39;CP949&#39;)
</code></pre>

<pre><code class="r"># 광역시도명만 추출합니다.
sidoGb &lt;- sido@data[, c(&#39;SIDO_CD&#39;, &#39;SIDO_NM&#39;)]
colnames(x = sidoGb) &lt;- c(&#39;sidoCd&#39;, &#39;sidoNm&#39;)

# spSigg@data에 sidoGb를 병합합니다.
spSigg@data &lt;- 
  merge(x = spSigg@data, 
        y = sidoGb, 
        by = &#39;sidoCd&#39;, 
        all.x = TRUE)

# 컬럼 순서를 변경합니다. 
spSigg@data &lt;- spSigg@data[, c(2:5, 1, 6)]

# sidoNm과 siggNm을 합친 areaNm 컬럼을 생성합니다.
spSigg@data$areaNm &lt;- str_c(spSigg@data$sidoNm, spSigg@data$siggNm, sep = &#39; &#39;)
</code></pre>

<p>이제 해야 할 일은 첫 번째 포스팅에서 저장했던 선거 결과 객체가 담긴 RDS 파일을 불러오는 일입니다.</p>

<pre><code class="r"># 데이터가 저장된 폴더로 작업경로를 변경합니다. 
setwd(dir = &#39;RDS가 저장된 폴더를 지정하세요&#39;)

# RDS 파일을 읽습니다.
result &lt;- readRDS(file = &#39;2017_Presidential_Election_Result.RDS&#39;)
</code></pre>

<p>선거 결과 데이터와 지금까지 작업한 <code>spSigg@data$areaNm</code>과 서로 같은지 교집합 원소의 개수를 확인해보겠습니다. <code>250</code>이면 모든 원소가 다 겹치는 것입니다.</p>

<pre><code class="r"># 선거결과 데이터의 지역명과 spSigg@data$areaNm이 서로 같은지 확인합니다.
intersect(x = result$지역명, 
          y = spSigg@data$areaNm %&gt;% unique() %&gt;% sort()) %&gt;% length()
</code></pre>

<pre><code>## [1] 250
</code></pre>

<p>다행하게도 <code>250</code>이 출력되었습니다.</p>

<p>드디어 행정경계구역 데이터 전처리 마지막 단계에 도달했습니다. <code>result</code> 객체에서 <code>후보자별 득표율</code>, <code>최대R</code>, <code>색상</code> 및 시청/군청/구청명으로 받아놓은 위경도 좌표 <code>lon</code>과 <code>lat</code> 컬럼을 <code>spSigg@data</code>에 병합합니다.</p>

<pre><code class="r"># spSigg@data에 선거 결과 데이터를 붙입니다. 
spSigg@data &lt;- 
  merge(x = spSigg@data, 
        y = result[, c(1, 22:30)], 
        by.x = &#39;areaNm&#39;, 
        by.y = &#39;지역명&#39;, 
        all.x = TRUE)

# 컬럼 순서를 변경합니다. 
spSigg@data &lt;- spSigg@data[, c(2:7, 1, 8:16)]

# FID 순서로 내림차순 정렬합니다. 
spSigg@data &lt;- spSigg@data %&gt;% arrange(FID)
</code></pre>

<p>이로써 전처리 과정이 모두 완료되었습니다. 이제 <code>spSigg</code> 객체를 RDS 파일로 저장합니다.</p>

<pre><code class="r"># RDS로 저장합니다.
saveRDS(object = spSigg, file = &#39;spSigg for leaflet.RDS&#39;)
</code></pre>

<h2>leaflet 패키지를 활용한 지도 시각화</h2>

<p><strong>Environment</strong> 패널이 텅 비었다고 가정하고 방금 저장한 RDS 파일을 불러오도록 하겠습니다.</p>

<pre><code class="r"># 데이터가 저장된 폴더로 작업경로를 변경합니다. 
setwd(dir = &#39;RDS가 저장된 폴더를 지정하세요&#39;)

# RDS 파일을 읽습니다.
spSigg &lt;- readRDS(file = &#39;spSigg for leaflet.RDS&#39;)
</code></pre>

<p><strong>leaflet</strong> 패키지를 이용하면 움직이는 지도 시각화를 할 수 있습니다. 함수는 아주 간단합니다. 자세한 내용이 필요하신 분은 별도로 찾아보시기 바랍니다. 지도 시각화는 두 가지를 선보이도록 하겠습니다.</p>

<ol>
<li> 시/군/구청 위치에 작은 원을 출력하고, 그 원을 출력하면 팝업이 생겨 후보별 득표율이 보이도록 합니다.</li>
<li> 단계구분도를 그리고 최다 득표 정당 색으로 채운 뒤, 다각형을 클릭하면 후보별 득표율이 저장된 팝업을 띄웁니다.</li>
</ol>

<p>먼저 <strong>leaflet</strong> 패키지를 불러온 뒤 첫 번째 코드를 실행하겠습니다.</p>

<pre><code class="r"># 필요 패키지를 불러옵니다.
library(leaflet)
</code></pre>

<pre><code class="r"># 시/군/구청 위치에 작은 원을 그리고 클릭하면 팝업이 생기도록 설정합니다.
spSigg %&gt;% 
  leaflet() %&gt;% 
  setView(
    lng = median(x = spSigg@data$lon),
    lat = median(x = spSigg@data$lat),
    zoom = 7) %&gt;% 
  addProviderTiles(provider = &#39;CartoDB.Positron&#39;) %&gt;% 
  addCircles(
    lng = ~ lon,
    lat = ~ lat,
    radius = ~ exp(x = 7),
    weight = 1,
    color = &#39;black&#39;,
    opacity = 1.0, 
    popup = ~ str_c(&#39;[&#39;, areaNm, &#39;] &#39;, &#39;문재인 : &#39;, 문재인R, &#39;, &#39;, &#39;홍준표 : &#39;, 홍준표R),
    fillColor = ~ 색상,
    fillOpacity = 0.5)
</code></pre>

<iframe src="https://drkevin.shinyapps.io/2017_Korean_Presidential_Election_Result/" height="480" width="740" frameborder="0" allowfullscreen></iframe>

<p>마지막으로 두 번째 코드를 실행하겠습니다.</p>

<pre><code class="r"># 지방자치단체 경계구역 데이터로 다각형을 만들어 단계구분도를 그리고 
# 다각형을 클릭하면 팝업이 생기도록 설정합니다.
spSigg %&gt;% 
  leaflet() %&gt;% 
  setView(
    lng = median(x = spSigg@data$lon),
    lat = median(x = spSigg@data$lat),
    zoom = 7) %&gt;% 
  addProviderTiles(provider = &#39;CartoDB.Positron&#39;) %&gt;% 
  addPolygons(
    weight = 1,
    smoothFactor = 0.5,
    color = &#39;black&#39;,
    opacity = 1.0, 
    popup = ~ str_c(&#39;[&#39;, areaNm, &#39;] &#39;, &#39;문재인 : &#39;, 문재인R, &#39;, &#39;, &#39;홍준표 : &#39;, 홍준표R),
    fillColor = ~ 색상, 
    fillOpacity = 0.5)
</code></pre>

<iframe src="https://drkevin.shinyapps.io/2017_Korean_Presidential_Election_Result_Leaflet/" height="480" width="740" frameborder="0" allowfullscreen></iframe>

<p>위에서 보이는 지도 이미지는 <strong>shinyapps.io</strong>에 별도로 올린 뒤 <iframe>으로 삽입한 것입니다. shinyapps.io에 올린 이미지는 작게 등록되기 때문에 답답한 면이 있는데요. 이를 해소하는 방법으로 <strong>RPubs</strong>로 게시하는 것입니다. <a href="http://rpubs.com/drkevin">여기</a>를 클릭하면 화면 전체 크기의 지도를 확인할 수 있습니다.</p>

<p>이로써 선거 결과 지도 시각화를 3회에 걸쳐 모두 마무리하였습니다. 번외로 <strong>선거관리위원회 홈페이지</strong>에서 제공되고 있는 선거 결과 데이터를 크롤링하는 포스팅을 소개하는 것으로 끝내겠습니다.</p>

</body>

</html>
