---
title: "R을 활용한 머신러닝"
author: "Dr.Kevin"
date: "1/2/2018"
output: 
  md_document: 
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 개요

  - 본 자료는 2017년 사내 임직원 대상 R 강의용으로 작성된 자료를 2018년 강의에 맞춰 업데이트한 것입니다.  
  - 다양한 기계학습 알고리즘을 이해한 후 실습을 통해 숙달함으로써 개인 프로젝트를 수행할 수 있는 기초를 다지는 것을 목표로 합니다.  
  - 기계학습은 크게 지도학습(Supervised Learning), 비지도학습(Unsupervised Learning), 그리고 강화학습(Reinforcement Learning)으로 나뉩니다.  
  - 또는 예측(Prediction) 모델링과 분류(Classification) 모델링으로도 구분할 수 있습니다.  
  - 본 강의 자료를 통해 지도학습과 비지도학습의 일부 알고리즘으로 예측 및 분류모델링을 학습하게 됩니다.  


## 목차

1. R 기초 (자료형 소개, indexing 및 slicing 등)  
1. R 웹크롤러 (GET, POST, User-agent, JavaScript, RSelenium 등)  
1. 탐색적 데이터 분석 (Explorative Data Analysis)  
1. 데이터 시각화 1 (Data Visualization 1)  
1. 데이터 시각화 2 (Data Visualization 2)  
1. 주성분분석 (PCA), 요인분석 (FA), 다차원척도법 (MDS)  
1. 군집분석 (Clustering)  
1. K근접이웃(KNN), 나이브 베이즈(Naive Bayes)  
1. 의사결정나무 (Decision Tree)  
1. 상관분석 (Correlation Analysis)  
1. 회귀분석 1 (Linear Regression)  
1. 회귀분석 2 (Linear Regression with variable selection)  
1. 로지스틱 회귀분석 (Logistic Regression)  
1. 랜덤포레스트 (Random Forest)  
1. 서포트벡터머신 (Support Vector Machine)  
